### ISSUE TITLE
Bad

### ISSUE THREAD

**Issue by kiancaine** [InFamousDino/Hob-Bot#2]
Hob is so cool, I lost wob though

**Comment by InFamousDino** [comment]
thanks kian well wob is now long gone

**Comment by RGooders** [comment]
ok.

**Comment by TheCakeChicken** [comment]
wobwobwob

**Comment by InFamousDino** [comment]
wob wob wob!?!??!

**Comment by HarryXChen3** [comment]
the what now

**Comment by RGooders** [comment]
PRISM, as its clumsy name suggests, is nothing more than a glorified modification of the popular Adonis admin commands that connects to a separate and independently managed server through Httpservice. Not only is PRISM designed in a way where significant security flaws exist in the form of LoadstringEnabled() being set to true and potential limitations on the gameplay due to poorly built-in anti-exploit mechanics, but also designed by a team of developers intent on advancing their self-interest over the will of the group by putting in as little effort into group projects as possible. For me, the constant kicking of BHNPS players when it was big was enough for me to believe that PRISM is detrimental in more way then one of gameplay. It is a shame that it is the official Plasma anti-exploit system.

**Comment by HarryXChen3** [comment]
https://www.urbandictionary.com/define.php?term=PRISM

**Comment by InFamousDino** [comment]
AAAAAAAAAAAAAAAAAAAAAAA
